app/urls.py
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static

from . import views
urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('blog', views.blog, name='blog'),
    path('contact', views.contact, name='contact'),
    path('services', views.services, name='services'),
    path('general_construction', views.general_construction, name='general_construction'),
    path('property_maintenance', views.property_maintenance, name='property_maintenance'),
    path('project_managment', views.project_managment, name='project_managment'),
    path('virtual_design_build', views.virtual_design_build, name='virtual_design_build'),
    path('preconstruction', views.preconstruction, name='preconstruction'),
    path('design_build', views.design_build, name='design_build'),
    path('blog_single', views.blog_single, name='blog_single'),
    path('projects_single/<int:pk>', views.projects_single, name='projects_single'),
    path('team_single', views.design_build, name='team_single'),
    path('success_page', views.success_page, name='success_page'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
    

construction/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("app.urls")),
]

app/models.py
from django.db import models
from ckeditor.fields import RichTextField
class Customer(models.Model):
    name = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=20)
    email = models.EmailField()
    address = models.CharField(max_length=200)
    service = models.CharField(max_length=100)
    date_requested = models.DateTimeField(auto_now_add=True)
    
class LatestProject(models.Model):
    feature_image=models.ImageField(upload_to="LatestProject/feature_image", help_text='image size must should be 601 X 399 px & 583 X 583 Px')
    project_name=models.CharField(max_length=100)
    location=models.CharField(max_length=100)
    project_start_date=models.CharField(max_length=100)
    project_end_date=models.CharField(max_length=100)
    about_the_project=RichTextField()
    def __str__(self):
        return self.project_name
    
class ProjectImage(models.Model):
    project_name=models.ForeignKey(LatestProject, on_delete=models.CASCADE)
    project_images=models.ImageField(upload_to="LatestProject/Project-Image", help_text='image size must should be 1200 X 650 px')

app/forms.py
from django import forms
from .models import Customer

class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ['name', 'phone_number', 'email', 'address', 'service']

app/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from .forms import CustomerForm
from .models import *
# Create your views here.

def index(request):
    
    #form
    if request.method == 'POST':
        form = CustomerForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('success_page') # redirect to a success page
    else:
        form = CustomerForm()
    
    #  View our latest projects.
    projects=LatestProject.objects.all()   
    context={
        'form': form,
        'projects':projects,
    }
    
    return render(request, 'index.html', context)

def success_page(request):
    return render(request, 'success_page.html')

def about(request):
    return render(request, 'about.html')

def blog(request):
    return render(request, 'blog.html')

def contact(request):
    return render(request, 'contact.html')

def services(request):
    return render(request, 'services.html')

def services(request):
    return render(request, 'services.html')

def general_construction(request):
    return render(request, 'general-construction.html')

def property_maintenance(request):
    return render(request, 'property-maintenance.html')

def project_managment(request):
    return render(request, 'project-managment.html')

def virtual_design_build(request):
    return render(request, 'virtual-design-build.html')

def preconstruction(request):
    return render(request, 'preconstruction.html')

def design_build(request):
    return render(request, 'design-build.html')



def blog_single(request):
    return render(request, 'blog-single.html')

def projects_single(request, pk):
    poject_view=LatestProject.objects.get(pk=pk)
    context={
        'poject_view':poject_view
    }
    return render(request, 'projects-single.html', context)

def team_single(request):
    return render(request, 'team-single.html')

templates/about.html
{% extends 'base.html' %}
 {% load static %}

{% block content %}

<!-- Breadcrumbs Start -->
<div class="rs-breadcrumbs img1">
    <div class="container">
        <div class="breadcrumbs-inner">
            <h1 class="page-title">
                   About Us
            </h1>
            <span class="sub-text">Excepteur sint occaecat cupidatat non proident, sunt in coulpa qui official<br> 
            modeserunt mollit anim id est 20 years experience.</span>
            <ul class="breadcrumbs-area">
               <li title="Go to konstruk">
                   <a class="active" href="index-2.html">Home</a>
               </li>
              <li>About</li>
           </ul>
        </div>
    </div>
</div>
<!-- Breadcrumbs End -->

<!-- About Start -->
<div class="rs-about about-style1 bg1 pt-120 pb-120 md-pt-80 md-pb-75">
    <div class="container">
        <div class="row y-middle">
            <div class="col-lg-6 md-mb-50">
                <div class="images-part">
                    <img src="{% static 'assets/images/about/style1/about.png'  %}" alt="About">
                </div>
            </div>
            <div class="col-lg-6 pl-50 md-pl-15">
                <div class="sec-title">
                    <span class="sub-text">
                        <img src="{% static 'assets/images/shape-1.png'  %}" alt="Images">
                        Who We Are
                    </span>
                    <h2 class="title pb-20">
                        Construction solutions focused future ready
                    </h2>
                    <p class="desc pb-37">
                        Leverage agile frameworks to provide a robust synopsis for high 
                        level overviews. Iterative approaches to corporate strategy data 
                        foster to collaborative thinking to empowerment.
                    </p>
                    <div class="row y-middle">
                        <div class="col-lg-4 col-md-4 sm-mb-30">
                            <div class="about-img">
                                <img src="{% static 'assets/images/about/style1/abzt.jpg'  %}" alt="About">
                            </div>
                        </div>
                        <div class="col-lg-8 col-md-8">
                            <ul class="check-lists">
                                <li class="list-item">
                                    <span class="icon-list-icon">
                                        <i class="fa fa-check-circle"></i>						
                                    </span>
                                    <span class="list-text">Pre-construction services</span>
                                </li>
                                <li class="list-item">
                                    <span class="icon-list-icon">
                                        <i class="fa fa-check-circle"></i>						
                                    </span>
                                    <span class="list-text">Industrial manufacturing</span>
                                </li>
                                <li class="list-item">
                                    <span class="icon-list-icon">
                                        <i class="fa fa-check-circle"></i>						
                                    </span>
                                    <span class="list-text">Building and construction</span>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="row mt-47 md-mt-25">
                        <div  class="col-lg-6 col-md-4 sm-mb-30">
                            <div class="btn-part">
                                <a class="readon more know" href="about.html">Know more</a>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-8">
                            <div class="signeture-img">
                                <img src="{% static 'assets/images/about/style1/signeture1.png'  %}" alt="Images">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- About End -->

<!-- Skillbar Choose Start -->
<div class="rs-skillbar skillbar-style1 skillbar-modify5 bg22 pt-120 pb-120">
    <div class="container">
        <div class="row y-middle">
            <div class="col-lg-6 pr-60 md-pr-15 mt-40 md-mb-40">
                <div class="sec-title mb-45">
                    <h2 class="title title4 pb-30">
                        Our management skills and work
                        experience
                    </h2>
                    <p class="desc desc8">
                        Podcasting operational change management inside of workflows to<br> 
                        establish a framework. Taking seamless key performance.
                    </p>
                </div>
                <!-- Skillbar Section Start -->
                <div class="cl-skill-bar">
                    <!-- Start Skill Bar -->
                    <span class="skillbar-title">Planning</span>
                    <div class="skillbar" data-percent="85">
                        <p class="skillbar-bar"></p>
                        <span class="skill-bar-percent">85%</span> 
                    </div> 
                    <!-- Start Skill Bar -->
                    <span class="skillbar-title">Design</span>
                    <div class="skillbar" data-percent="95">
                        <p class="skillbar-bar"></p>
                        <span class="skill-bar-percent">95%</span> 
                    </div> 
                    <!-- Start Skill Bar -->
                    <span class="skillbar-title">Development</span>
                    <div class="skillbar" data-percent="75">
                        <p class="skillbar-bar"></p>
                        <span class="skill-bar-percent">75%</span> 
                    </div> 
                    <!-- Start Skill Bar -->
                    <span class="skillbar-title">Delivery</span>
                    <div class="skillbar" data-percent="90">
                        <p class="skillbar-bar"></p>
                        <span class="skill-bar-percent">90%</span> 
                    </div>
                </div>
                <!-- Skillbar Section End -->
            </div>
            <div class="col-lg-6 video-img">
                <div class="rs-videos">
                    <div class="animate-border">
                        <a class="popup-border popup-videos" href="https://www.youtube.com/watch?v=FMvA5fyZ338">
                            <i class="fa fa-play"></i>
                        </a>
                    </div>    
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Skillbar Choose End -->



<!-- Call To Action Choose Start -->
<div class="rs-cta bg4 pt-120 pb-115 md-pt-80 md-pb-75">
    <div class="container">
        <div class="call-action">
            <div class="sec-title text-center">
                <span class="sub-text yellow-color">
                    Work With Us !
                </span>
                <h2 class="title white-color pb-20">
                    Have any upcoming project
                </h2>
                <p class="desc desc3 pb-35">
                    Leverage agile frameworks to provide a robust synopsis for high level overviews.<br> 
                    Iterative approaches to corporate strategy foster collaborative thinking
                </p>
                <div class="btn-part">
                    <a class="readon more contact" href="contact.html">Get Started</a>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Call To Action Choose End -->

{% endblock %}

templates/projects-single.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- Breadcrumbs Start -->
<div class="rs-breadcrumbs img1">
    <div class="container">
        <div class="breadcrumbs-inner">
            <h1 class="page-title">
                   Projects Single
            </h1>
            <span class="sub-text">Excepteur sint occaecat cupidatat non proident, sunt in coulpa qui official<br> 
            modeserunt mollit anim id est 20 years experience.</span>
            <ul class="breadcrumbs-area">
               <li title="Go to konstruk">
                   <a class="active" href="index-2.html">Home</a>
               </li>
              <li>Projects Single</li>
           </ul>
        </div>
    </div>
</div>
<!-- Breadcrumbs End -->

<!-- Slider Section Start -->
<div class="rs-slider case-slider-style3 pt-120 md-pt-80">
    <div class="container">
        <div class="rs-carousel owl-carousel" data-loop="true" data-items="1" data-margin="0" data-autoplay="true" data-hoverpause="true" data-autoplay-timeout="5000" data-smart-speed="800" data-dots="false" data-nav="false" data-nav-speed="false" data-center-mode="false" data-mobile-device="1" data-mobile-device-nav="false" data-mobile-device-dots="false" data-ipad-device="1" data-ipad-device-nav="true" data-ipad-device-dots="false" data-ipad-device2="1" data-ipad-device-nav2="true" data-ipad-device-dots2="false" data-md-device="1" data-md-device-nav="true" data-md-device-dots="false">
            <div class="slider-img">
                {% for project_image in poject_view.projectimage_set.all %}
    <img src="{{ project_image.project_images.url }}" alt="Slider">
{% endfor %}

            </div>
        </div>
    </div>
</div>
<!-- Slider Section End -->

<!-- Project Details Section Start -->
<div class="rs-project-details pt-70 md-pt-80">
    <div class="container">
        <div class="project-information mb-45">
            <div class="row">
                <div class="col-lg-3 col-md-6 md-mb-30">
                    <div class="project-content">
                        <div class="project-right-border"></div>
                        <h4 class="title">Skills</h4>
                        <div class="description">
                            <p>Consulting, Management</p>            		
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 md-mb-30 pl-50 md-pl-15">
                    <div class="project-content">
                        <div class="project-right-border border-two"></div>
                        <h4 class="title">Start Date</h4>
                        <div class="description">
                            <p>{{poject_view.project_start_date}}</p>            		
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 sm-mb-30">
                    <div class="project-content">
                        <div class="project-right-border border-three"></div>
                        <h4 class="title">Completed Date</h4>
                        <div class="description">
                            <p>{{poject_view.project_end_date}}</p>            		
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="project-content">
                        <h4 class="title">Location</h4>
                        <div class="description">
                            <p>{{poject_view.project_name}}, {{poject_view.location}}</p>            		
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="project-txt mb-30">
            <div class="desc">
                {{poject_view.about_the_project | safe}}
            </div>
        </div>
        <!-- Counter Section Start -->
        <div class="rs-counter counter-style6">
            <div class="counter-top bg23 md-pt-80 md-pb-80">
                <div class="row">
                    <div class="col-lg-3 col-md-6 md-mb-40">
                        <div class="rs-counter-list">
                            <div class="counter-text">
                                <div class="counter-icon">
                                    <img src="{% static 'assets/images/counter/pro-single/icons1.png' %}" alt="">
                                </div>
                                <div class="counter-number">
                                    <span class="rs-count">1500</span>
                                    <span class="prefix">+</span>
                                </div>
                                <span class="title">Satisfied clients</span>	
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 md-mb-40">
                        <div class="rs-counter-list">
                            <div class="counter-text">
                                <div class="counter-icon">
                                    <img src="{% static 'assets/images/counter/pro-single/icons2.png' %}" alt="">
                                </div>
                                <div class="counter-number">
                                    <span class="rs-count">2070</span>
                                    <span class="prefix">+</span>
                                </div>
                                <span class="title">Order Served</span>	
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 sm-mb-40">
                        <div class="rs-counter-list">
                            <div class="counter-text">
                                <div class="counter-icon">
                                    <img src="{% static 'assets/images/counter/pro-single/icons3.png' %}" alt="">
                                </div>
                                <div class="counter-number">
                                    <span class="rs-count">6080</span>
                                    <span class="prefix">+</span>
                                </div>
                                <span class="title">5 Star Received</span>	
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 ">
                        <div class="rs-counter-list">
                            <div class="counter-text">
                                <div class="counter-icon">
                                    <img src="{% static 'assets/images/counter/pro-single/icons4.png' %}" alt="">
                                </div>
                                <div class="counter-number">
                                    <span class="rs-count">300</span>
                                    <span class="prefix">+</span>
                                </div>
                                <span class="title">Happy Customers</span>	
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Counter Section End -->

        <div class="rs-project-goals pt-115 md-pt-75">
            <div class="row y-middle">
                <div class="col-lg-6 pr-50 md-pr-15 md-mb-30">
                    <div class="project-content mb-45">
                        <div class="project-title">
                            <h2 class="title pb-35">Project Goals</h2>
                        </div>
                        <div class="desc pb-30">
                            European languages are members of the same family. The languages only differ in their grammar, their pronu nciation and their most common words.. are of the same family.  
                        </div>
                        <ul class="check-lists check-lists3 check-single">                              
                            <li>Digital  how will activities impact traditional</li>
                               <li>All these digital elements and projects aim</li>
                               <li>I monitor my staff with software that takes</li>          
                               <li>Laoreet dolore magna sodium glutimate</li>          
                               <li>Veniam Minim quis niacin sodium</li>          
                        </ul>
                        <div class="desc pt-20">
                            Pronunciation and more common words. If several languages the coalesce.  over the years, sometimes by accident, sometimes on purpose. Over the years, sometimes by  purpose.  
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="project-goal">
                        <img src="{% static 'assets/images/project/details/pro-img1.jpg' %}" alt="">
                    </div>
                </div>
            </div>
            <div class="outcome-project pt-90 md-pt-80 pb-90 md-pb-80">
                <div class="row y-middle">
                    <div class="col-lg-6 md-mb-30">
                        <div class="rs-videos career-style1">
                            <div class="images-video">
                                <img src="{% static 'assets/images/project/details/pro-video.png' %}" alt="">
                            </div>
                            <div class="overly-border">
                                <a class="popup-videos" href="https://www.youtube.com/watch?v=LpdRAyIGg8I">
                                    <i class="fa fa-play"></i>
                                </a>
                            </div>    
                        </div>
                    </div>
                    <div class="col-lg-6 pl-45 md-pl-15 mt-55">
                        <div class="project-content mb-45 md-mb-0">
                            <div class="project-title">
                                <h2 class="title pb-35">Final Outcome of This Project</h2>
                            </div>
                            <div class="desc pb-20">
                                The languages only differ in their grammar, their pronu nciation and their most common words. sometimes by accident, sometimes on purpose. European languages are members of the same family european languages are members of the same family. 
                            </div>
                            <ul class="check-lists check-lists3 check-single">                              
                                <li>How will digital activities impact traditional manufacturing.</li>
                                   <li>All these digital elements and projects aim to enhance .</li>
                                   <li>I monitor my staff with software that takes screenshots.</li>          
                                   <li>Dolore magna niacin sodium aliquam hendrerit.</li>          
                                   <li>Minim veniam quis niacin nostrud exerci dolor.</li>          
                            </ul>
                            <div class="desc pt-20">
                                If several languages coalesce.  over the years, sometimes by accident, sometimes on purpose. Over the years, sometimes by accident, on purpose uropean languages the same family  
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Call To Action Choose Start -->
    <div class="rs-cta bg4 pt-120 pb-120 md-pt-80 md-pb-80">
        <div class="container">
            <div class="call-action">
                <div class="sec-title text-center">
                    <span class="sub-text yellow-color">
                        Work With Us !
                    </span>
                    <h2 class="title white-color pb-20">
                        Have any upcoming project
                    </h2>
                    <p class="desc desc3 pb-35">
                        Leverage agile frameworks to provide a robust synopsis for high level overviews.<br> 
                        Iterative approaches to corporate strategy foster collaborative thinking
                    </p>
                    <div class="btn-part">
                        <a class="readon more contact" href="contact.html">Get Started</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Call To Action Choose End -->
</div>
<!-- Project Details Section End -->

{% endblock %}

templates/success_page.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<h2 style="color: green; text-align: center;">Thank You for Requesting Our Services</h2>
<p style="text-align: center;">We will get back to you as soon as possible. 😊</p>


{% endblock %}